const CommunityTypes = {
  FETCH_NEAR_PEOPLE: "FETCH_NEAR_PEOPLE",
  FETCH_NEAR_PEOPLE_ERROR: "FETCH_NEAR_PEOPLE_ERROR",
  FETCH_NEAR_PEOPLE_SUCCESS: "FETCH_NEAR_PEOPLE_SUCCESS",
};

export default CommunityTypes;
