const CommunityTypes = {
  FETCH_NEAR_PEOPLE: "FETCH_NEAR_PEOPLE",
  FETCH_NEAR_PEOPLE_ERROR: "FETCH_NEAR_PEOPLE_ERROR",
  FETCH_NEAR_PEOPLE_SUCCESS: "FETCH_NEAR_PEOPLE_SUCCESS",
  GET_PROFILE_REQUEST : "GET_PROFILE_REQUEST",
  GET_PROFILE_SUCCESS : "GET_PROFILE_SUCCESS",
  GET_PROFILE_ERROR : "GET_PROFILE_ERROR",
};

export default CommunityTypes;
