const SongTypes = {
  FETCH_SONG_REQUEST: "FETCH_SONG_REQUEST",
  FETCH_SONG_ERROR: "FETCH_SONG_ERROR",
  FETCH_SONG_SUCCESS: "FETCH_SONG_SUCCESS",
  

  ADD_LOCAL_RECIPE_COMMENT: "ADD_LOCAL_RECIPE_COMMENT",
  RECIPE_UPDATING: "RECIPE_UPDATING",
  RECIPE_UPDATING_ERROR: "RECIPE_UPDATING_ERROR",
};

export default SongTypes;
